package com.example.FoodHub.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
@Getter
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "Lỗi không xác định", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_EXISTED(1001, "Tên người dùng đã tồn tại", HttpStatus.BAD_REQUEST),
    USER_NOT_EXISTED(1002, "Không tìm thấy người dùng", HttpStatus.NOT_FOUND),
    PASSWORD_INVALID(1003, "Mật khẩu phải có ít nhất {min} ký tự", HttpStatus.BAD_REQUEST),
    USERNAME_INVALID(1004, "Tên người dùng phải có ít nhất {min} ký tự", HttpStatus.BAD_REQUEST),
    INVALID_KEY(1005, "Khóa không hợp lệ", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1006, "Chưa xác thực", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1007, "Không được phép", HttpStatus.FORBIDDEN),
    INTERNAL_SERVER_ERROR(1008, "Lỗi máy chủ nội bộ", HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_NOT_EXISTED(1009, "Không tìm thấy Role", HttpStatus.NOT_FOUND),
    TABLE_NOT_EXISTED(1010, "Không tìm thấy bàn", HttpStatus.NOT_FOUND),
    ORDER_NOT_EXISTED(1011, "Không tìm thấy đơn hàng", HttpStatus.NOT_FOUND),
    MENU_ITEM_NOT_EXISTED(1012, "Không tìm thấy món ăn", HttpStatus.NOT_FOUND),
    ORDER_ITEMS_REQUIRED(1013, "Yêu cầu có món trong đơn hàng", HttpStatus.BAD_REQUEST),
    ORDER_ITEM_NOT_EXISTED(1014, "Không tìm thấy món trong đơn hàng", HttpStatus.NOT_FOUND),
    ORDER_CANNOT_BE_UPDATED(1015, "Không thể cập nhật đơn hàng", HttpStatus.BAD_REQUEST),
    TABLE_NOT_AVAILABLE(1016, "Bàn không khả dụng", HttpStatus.BAD_REQUEST),
    MENU_ITEM_NOT_AVAILABLE(1017, "Món ăn không khả dụng", HttpStatus.BAD_REQUEST),
    INVALID_STATUS_TRANSITION(1018, "Chuyển trạng thái không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST(1019, "Yêu cầu không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_TABLE_STATUS(1020, "Trạng thái bàn không hợp lệ", HttpStatus.BAD_REQUEST),
    TABLE_NUMBER_INVALID(1021, "Số bàn không được để trống", HttpStatus.BAD_REQUEST),
    QR_CODE_INVALID(1022, "Mã QR không được để trống", HttpStatus.BAD_REQUEST),
    AREA_INVALID(1023, "Khu vực phải là chữ cái và không được để trống", HttpStatus.BAD_REQUEST),
    TABLE_ID_REQUIRED(1024, "Yêu cầu ID bàn", HttpStatus.BAD_REQUEST),
    TABLE_ID_INVALID(1025, "ID bàn phải là số dương", HttpStatus.BAD_REQUEST),
    USER_ID_REQUIRED(1026, "Yêu cầu ID người dùng", HttpStatus.BAD_REQUEST),
    USER_ID_INVALID(1027, "ID người dùng phải là số dương", HttpStatus.BAD_REQUEST),
    NOTE_TOO_LONG(1028, "Ghi chú không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    ORDER_TYPE_INVALID(1029, "Loại đơn hàng phải là DINE_IN, TAKEAWAY hoặc DELIVERY", HttpStatus.BAD_REQUEST),
    ORDER_STATUS_INVALID(1030, "Trạng thái đơn hàng không hợp lệ", HttpStatus.BAD_REQUEST),
    MENU_ITEM_ID_REQUIRED(1031, "Yêu cầu ID món ăn", HttpStatus.BAD_REQUEST),
    MENU_ITEM_ID_INVALID(1032, "ID món ăn phải là số dương", HttpStatus.BAD_REQUEST),
    QUANTITY_REQUIRED(1033, "Yêu cầu số lượng", HttpStatus.BAD_REQUEST),
    QUANTITY_INVALID(1034, "Số lượng phải ít nhất là 1", HttpStatus.BAD_REQUEST),
    QUANTITY_TOO_LARGE(1035, "Số lượng không được vượt quá 99", HttpStatus.BAD_REQUEST),
    PRICE_REQUIRED(1036, "Yêu cầu giá", HttpStatus.BAD_REQUEST),
    PRICE_INVALID(1037, "Giá phải lớn hơn 0", HttpStatus.BAD_REQUEST),
    PRICE_FORMAT_INVALID(1038, "Định dạng giá không hợp lệ", HttpStatus.BAD_REQUEST),
    ORDER_ITEM_STATUS_INVALID(1039, "Trạng thái món trong đơn hàng phải là PENDING, CONFIRMED, READY, CANCELLED hoặc COMPLETED", HttpStatus.BAD_REQUEST),
    INVALID_DOB(1008, "Tuổi của bạn phải ít nhất {min} tuổi", HttpStatus.BAD_REQUEST),
    MENU_ITEM_NOT_FOUND(1011, "Không tìm thấy món ăn", HttpStatus.NOT_FOUND),
    CATEGORY_NOT_FOUND(1012, "Không tìm thấy một hoặc nhiều danh mục", HttpStatus.NOT_FOUND),
    IMAGE_UPLOAD_FAILED(1013, "Tải hình ảnh thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_IMAGE_URL(1014, "Định dạng URL hình ảnh không hợp lệ", HttpStatus.BAD_REQUEST),
    MENU_ITEM_EXISTED(1015, "Món ăn đã tồn tại", HttpStatus.BAD_REQUEST),
    MENU_NAME_NOT_BLANK(1016, "Tên menu không được để trống", HttpStatus.BAD_REQUEST),
    MENU_NAME_SIZE(1017, "Tên menu phải có ít nhất 2 ký tự", HttpStatus.BAD_REQUEST),
    PRICE_NOT_NULL(1018, "Giá không được để trống", HttpStatus.BAD_REQUEST),
    PRICE_POSITIVE(1019, "Giá phải là số dương", HttpStatus.BAD_REQUEST),
    USERNAME_NOT_BLANK(1020, "Tên người dùng không được để trống", HttpStatus.BAD_REQUEST),
    ROLE_NOT_BLANK(1021, "Role không được để trống", HttpStatus.BAD_REQUEST),
    ADDRESS_NOT_BLANK(1022, "Địa chỉ không được để trống", HttpStatus.BAD_REQUEST),
    PHONE_NOT_BLANK(1023, "Số điện thoại không được để trống", HttpStatus.BAD_REQUEST),
    EMAIL_NOT_BLANK(1024, "Email không được để trống", HttpStatus.BAD_REQUEST),
    PASSWORD_NOT_BLANK(1025, "Mật khẩu không được để trống", HttpStatus.BAD_REQUEST),
    PHONE_PATTERN(1026, "Số điện thoại phải có đúng 10 chữ số", HttpStatus.BAD_REQUEST),
    INVALID_TABLE_ID(2000, "ID bàn không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_QR_TOKEN(2001, "Mã QR không hợp lệ", HttpStatus.UNAUTHORIZED),
    OCCUPIED_TABLE(2002, "Bàn đã được sử dụng", HttpStatus.BAD_REQUEST),
    INVALID_SESSION_ID(2003, "ID phiên không hợp lệ", HttpStatus.BAD_REQUEST),
    USER_HAS_SCHEDULED_SHIFTS(1040, "Người dùng có ca làm đã lên lịch và không thể bị vô hiệu hóa", HttpStatus.BAD_REQUEST),
    DUPLICATE_SHIFT(1042, "Tìm thấy ca làm trùng lặp cho người dùng trong cùng một ngày", HttpStatus.BAD_REQUEST),
    INVALID_SHIFT_TYPE(1043, "Loại ca làm không hợp lệ. Phải là morning, afternoon hoặc night", HttpStatus.BAD_REQUEST),
    USERNAME_SIZE(1045, "Tên người dùng phải có ít nhất 2 ký tự", HttpStatus.BAD_REQUEST),
    PASSWORD_SIZE(1047, "Mật khẩu phải có đúng 8 ký tự", HttpStatus.BAD_REQUEST),
    EMAIL_SIZE(1049, "Email phải có ít nhất 2 ký tự", HttpStatus.BAD_REQUEST),
    PHONE_SIZE(1051, "Số điện thoại phải có ít nhất 2 ký tự", HttpStatus.BAD_REQUEST),
    ADDRESS_SIZE(1053, "Địa chỉ phải có ít nhất 2 ký tự", HttpStatus.BAD_REQUEST),
    ROLE_NAME_NOT_BLANK(1054, "Tên Role không được để trống", HttpStatus.BAD_REQUEST),
    EMAIL_EXISTS(1056, "Email đã tồn tại", HttpStatus.BAD_REQUEST),
    ROLE_NAME_SIZE(1055, "Tên Role phải có ít nhất 2 ký tự", HttpStatus.BAD_REQUEST),
    OTP_NOT_FOUND(1060, "Không tìm thấy OTP", HttpStatus.NOT_FOUND),
    OTP_EXPIRED(1061, "OTP đã hết hạn", HttpStatus.BAD_REQUEST),
    OTP_ALREADY_VERIFIED(1062, "OTP đã được xác minh", HttpStatus.BAD_REQUEST),
    INVALID_OTP(1063, "OTP không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_ROLE(1064, "Role không hợp lệ", HttpStatus.BAD_REQUEST),
    PAYMENT_PENDING(1016, "Thanh toán đang chờ xử lý, vui lòng đợi xác nhận", HttpStatus.ACCEPTED),
    PAYMENT_FAILED(1017, "Thanh toán thất bại do {reason}", HttpStatus.BAD_REQUEST),
    INVALID_DATE_RANGE(1018, "Khoảng thời gian không hợp lệ, ngày kết thúc phải sau ngày bắt đầu", HttpStatus.BAD_REQUEST),
    ORDER_NOT_FOUND(1019, "Không tìm thấy đơn hàng", HttpStatus.NOT_FOUND),
    INSUFFICIENT_FUNDS(1020, "Không đủ tiền, vui lòng sử dụng phương thức thanh toán khác", HttpStatus.PAYMENT_REQUIRED),
    ORDER_COMPLETED(1021, "Đơn hàng không thể thanh toán ở trạng thái hiện tại: COMPLETED", HttpStatus.BAD_REQUEST),
    PAYMENT_NOT_FOUND(1022, "Không tìm thấy bản ghi thanh toán", HttpStatus.NOT_FOUND),
    INVALID_ORDER_AMOUNT(1023, "Số tiền đơn hàng không hợp lệ", HttpStatus.BAD_REQUEST),
    ORDER_ALREADY_CANCELED(1024, "Đơn hàng đã bị hủy", HttpStatus.BAD_REQUEST),
    PAYMENT_ALREADY_PROCESSED(1025, "Thanh toán đã được xử lý", HttpStatus.BAD_REQUEST),
    INVALID_PAYMENT_METHOD(1026, "Phương thức thanh toán không hợp lệ", HttpStatus.BAD_REQUEST),
    WORK_SCHEDULE_NOT_FOUND(1041, "Không tìm thấy lịch làm việc", HttpStatus.NOT_FOUND),
    PAST_SHIFT(1041, "Không thể tùy chỉnh lịch trong quá khứ", HttpStatus.BAD_REQUEST),
    SHIFT_NOT_FOUND(1044, "Không tìm thấy ca làm", HttpStatus.NOT_FOUND),
    PAST_DATE_NOT_ALLOWED(1046, "Không thể tạo hoặc xóa ca làm trong quá khứ", HttpStatus.BAD_REQUEST),
    PAST_SHIFT_TIME(1048, "Không thể tạo ca làm đã qua", HttpStatus.BAD_REQUEST),
    INVALID_TIME_FORMAT(1050, "Định dạng thời gian không hợp lệ, phải là HH:mm", HttpStatus.BAD_REQUEST),
    USER_NOT_ACTIVE(1052, "Người dùng không hoạt động", HttpStatus.BAD_REQUEST),
    PAYMENT_ALREADY_EXISTS(1057, "Thanh toán đã tồn tại cho đơn hàng này", HttpStatus.BAD_REQUEST),
    PAYMENT_URL_GENERATION_FAILED(1058, "Tạo URL thanh toán thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    PAYMENT_ALREADY_PAID(1059, "Thanh toán đã được thanh toán", HttpStatus.BAD_REQUEST),
    PAYMENT_EXPIRED(1065, "Thanh toán đã hết hạn", HttpStatus.BAD_REQUEST),
    SESSION_FINISH_EXCEPTION(2003, "Không thể kết thúc phiên", HttpStatus.BAD_REQUEST),
    CREATE_TABLE_TOKEN_FAILED(2004, "Tạo token bàn thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_TOKEN_TYPE(1042, "Loại token không hợp lệ", HttpStatus.UNAUTHORIZED),
    TABLE_OCCUPIED_CANNOT_DELETE(1043, "Bàn đang được sử dụng và không thể xóa", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED_ACCESS(1043, "Token không hợp lệ", HttpStatus.UNAUTHORIZED),
    CHAT_MESSAGES_NOT_FOUND(1044, "Không tìm thấy tin nhắn trò chuyện cho bàn được chỉ định", HttpStatus.NOT_FOUND),
    ORDER_NOT_MODIFIABLE(1060, "Đơn hàng không thể chỉnh sửa ở trạng thái hiện tại", HttpStatus.BAD_REQUEST),
    TOKEN_INVALIDATION_FAILED(1066, "Lỗi khi hủy token, vui lòng thử lại", HttpStatus.INTERNAL_SERVER_ERROR),
    TABLE_ALREADY_IN_USE(1067, "Bàn đã được sử dụng bởi khách khác", HttpStatus.BAD_REQUEST),
    WORK_SHIFT_LOG_NOT_FOUND(1045, "Không tìm thấy nhật ký ca làm", HttpStatus.NOT_FOUND),
    CHECKIN_TOO_EARLY(1046, "Không được check-in sớm quá 30 phút", HttpStatus.BAD_REQUEST),
    CHECKIN_TOO_LATE(1047, "Không thể check-in khi ca làm đã kết thúc", HttpStatus.BAD_REQUEST),
    USER_NOT_CHECKED_IN(1048, "Bạn chưa chấm công vào ca", HttpStatus.BAD_REQUEST),
    WORK_SHIFT_LOG_ALREADY_CHECK_IN(1049, "Bạn đã chấm công vào ca làm này rồi", HttpStatus.BAD_REQUEST),
    WORK_SHIFT_LOG_ALREADY_CHECK_OUT(1050, "Bạn đã chấm công ra khỏi ca làm này rồi", HttpStatus.BAD_REQUEST),
    ;

    private int code;
    private String message;
    private HttpStatusCode statusCode;

    ErrorCode(int code, String message, HttpStatusCode statusCode) {
        this.code = code;
        this.message = message;
        this.statusCode = statusCode;
    }
}
